### PR TITLE
Refactor to support testing

### PR DESCRIPTION
**Pull request by eenblam**
Work in progress. PR opened for review/comments as I go.

Hoping to have full test suite + Travis + CD to Heroku in place on merge.

So far:

- Replace var with const or let where appropriate
- Break out non-IO logic into pure functions in util.js
- Add docstrings
- Add Jasmine as a dev dependency
- Add a few simple tests to confirm Jasmine is working
- Add TODOs to be completed before merging

### CODE REVIEW

**Comment by bennlich** [comment]
Sorry for the delayed reply. This is very cool! Looks like you're setting us up for success :-)

> Hoping to have full test suite + Travis + CD to Heroku in place on merge.

Maybe worth merging sooner rather than later? I think it's okay to merge in incomplete pieces as long as nothing is broken. It's maybe better, even, to merge early so as to avoid staleness. (E.g. stuff can rapidly get annoying if I start to do my own refactoring and push to master while this PR sits here.)

**Comment by eenblam** [comment]
> Maybe worth merging sooner rather than later?

@bennlich I'm making some breaking changes that will also require updating the monitor script running on the exit node. I'd rather keep that confined to a branch until it's all ready to go in one place.

There's a lot of weirdness in the original code. For example, updates are actually just checks on GET requests to see which IP they came from instead of authenticating POSTs. As a result, updates from the exit node just receive a web page as a reply instead of an API response. This isn't really a problem at the moment, since the exit node doesn't care if monitoring is up or not - it will keep plugging along. However, I don't think it gives us a good platform to expand upon, so I'm trying to fix it sooner rather than later.

I've also been MIA on this for over a week, but picking it back up presently.

**Comment by jhpoelen** [comment]
@eenblam Thanks for putting in these changes. fyi - the GET update is a convenient way to get information across and you can test easily it in a browser. However, I am not opposed to introduce a POST method. 

Overall, I would suggest to make incremental changes directly on master, and setup continuous testing/deployment. The tests should prevent any crazy changes from propagating to production.

If you are worried about breaking changes, I'd suggest to keep the old functionality in place until all scripts (currently only a single script, running against on my account on exitnode) are migrated over.  Perhaps worth considering to include the monitor script into https://github.com/sudomesh/exitnode/blob/master/src/etc/systemd/system/babeld-monitor.timer and related scripts.

**Comment by eenblam** [comment]
Needs work to account for recent upstream changes.

**Comment by jhpoelen** [comment]
Merging regardless of test failure. Will attempt to fix separately.

**Comment by jhpoelen** [comment]
so, I've attempted to merge the files, and upgraded the old exit node.

**Pull request merged**
