### PR TITLE
Totals by time interval

### PR DESCRIPTION
**Pull request by haydenhw**
For #35

### CODE REVIEW

**Comment by haydenhw** [comment]
I used the query in this commit to calculate node totals from this  [data sample](https://github.com/sudomesh/monitor/blob/master/test/monitor-db-dump.json) at 5 minute intervals and got these values: 
```
[ 40, 40, 40, 40, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41 ]
```
Does 40-41 total nodes seem about right?

**Comment by bennlich** [comment]
Yes! Haven't had a chance to look at the code yet, but those totals sound right. They more or less match up with the sum of nodes listed at the top of monitor.peoplesopen.net.

Screenshot_20191202-100109

**Comment by bennlich** [comment]
Love it! Merged in https://github.com/sudomesh/monitor/commit/f24b5dd3c331b30bef1afeea418c4f1e7c8a8064!

:100:

**Comment by bennlich** [comment]
Deployed! https://monitor.peoplesopen.net/

**Pull request closed without merging**
